field: 718dfac4-3256-4637-baa5-2164f07ce3c4 # Tarjetas de beneficios
fieldLayouts:
  7ece9853-9649-4708-bcbc-3fd17d0164dc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 87d4739a-ad6c-42ab-8e67-529a715a801e # Título del Beneficio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5764d1b2-c035-487e-ac2a-48bb3906c1bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 225c1958-5873-4e27-9bb8-6f30a217ce7c # Icono
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d601125-bf45-485f-aaa5-c92e5c474ebc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7d8cb225-2b9c-482e-8d7b-5ae2e194cb14 # Descripción del beneficio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44f8be84-eec4-4c4e-9498-551e120d40c7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 84397246-d601-4944-aa40-62a685a8a48d
        userCondition: null
fields:
  7d8cb225-2b9c-482e-8d7b-5ae2e194cb14: # Descripción del beneficio
    columnSuffix: urlftrdh
    contentColumnType: text
    fieldGroup: null
    handle: benefitDescription
    instructions: null
    name: 'Descripción del beneficio'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  87d4739a-ad6c-42ab-8e67-529a715a801e: # Título del Beneficio
    columnSuffix: jeykvkju
    contentColumnType: text
    fieldGroup: null
    handle: benefitTitle
    instructions: null
    name: 'Título del Beneficio'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  225c1958-5873-4e27-9bb8-6f30a217ce7c: # Icono
    columnSuffix: mklxegbg
    contentColumnType: text
    fieldGroup: null
    handle: benefitIcon
    instructions: 'Revisa las clases en fontawsome.com'
    name: Icono
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: benefitCard
name: 'Tarjeta de Beneficio'
sortOrder: 1
