fieldLayouts:
  c34b6490-3881-4fbd-917b-6004d8876eae:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
        name: Contenido
        sortOrder: 1
fs: cdn
handle: cdn
hasUrls: true
name: 'Imágenes públicas'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: '@web/assets/images/public_images'
