columnSuffix: ljqnvdnk
contentColumnType: text
fieldGroup: 90aa8e95-25e1-4c20-9526-31059ff11407 # New Services Model
handle: aboutServiceTitle
instructions: '(h2). Ponle un título a la sección ( A quién va dirigido)'
name: 'Título: Acerca del servicio'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
