columnSuffix: wpkjbdyy
contentColumnType: text
fieldGroup: 90aa8e95-25e1-4c20-9526-31059ff11407 # New Services Model
handle: aboutServiceDescription
instructions: 'Descripción justo debajo de su título'
name: 'Descripción: Acerca del Servicio'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 99d06683-b4dc-4996-af1e-a55db9b88f75 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
