columnSuffix: null
contentColumnType: text
fieldGroup: 16777690-1a83-4a23-aaf2-5138b7d2617e # Blog
handle: body
instructions: ''
name: 'Cuerpo del artículo'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 99d06683-b4dc-4996-af1e-a55db9b88f75 # Simple
  columnType: text
  defaultTransform: ''
  purifierConfig: ''
  purifyHtml: '1'
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showUnpermittedFiles: ''
  showUnpermittedVolumes: ''
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
