columnSuffix: null
contentColumnType: text
fieldGroup: 16777690-1a83-4a23-aaf2-5138b7d2617e # Blog
handle: body
instructions: null
name: 'Cuerpo del artículo'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 99d06683-b4dc-4996-af1e-a55db9b88f75 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
