contentColumnType: string
fieldGroup: c44e1865-5d0a-429d-be51-84af5e860f1a
handle: cover
instructions: 'Esta imagen aparecerá de portada en el detalle del servicio'
name: Portada
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:964c97bb-a9cc-4e56-9fea-cf94cd23bd3f' # Imágenes públicas
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:964c97bb-a9cc-4e56-9fea-cf94cd23bd3f' # Imágenes públicas
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
