columnSuffix: null
contentColumnType: string
fieldGroup: c44e1865-5d0a-429d-be51-84af5e860f1a # Servicios
handle: cover
instructions: 'Esta imagen aparecerá de portada en el detalle del servicio'
name: Portada
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:964c97bb-a9cc-4e56-9fea-cf94cd23bd3f' # Imágenes públicas
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:964c97bb-a9cc-4e56-9fea-cf94cd23bd3f' # Imágenes públicas
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
