columnSuffix: null
contentColumnType: string
fieldGroup: 366fe78c-c06c-49b9-b5a6-cb88a0d35c0e # Clientes
handle: logo
instructions: 'Añade el logotipo de tu cliente'
name: Logotipo
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:964c97bb-a9cc-4e56-9fea-cf94cd23bd3f' # Imágenes públicas
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:964c97bb-a9cc-4e56-9fea-cf94cd23bd3f' # Imágenes públicas
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
