contentColumnType: text
fieldGroup: 1fbf6371-1871-4eb1-85a2-532ba65a9ece
handle: pachucaAddress
instructions: ''
name: 'Dirección Pachuca'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
