columnSuffix: null
contentColumnType: text
fieldGroup: c44e1865-5d0a-429d-be51-84af5e860f1a # Servicios
handle: servDescription
instructions: 'Describe lo más detallado posible el servicio que ofreces'
name: 'Descripción del servicio'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 99d06683-b4dc-4996-af1e-a55db9b88f75 # Simple
  columnType: text
  defaultTransform: ''
  purifierConfig: ''
  purifyHtml: '1'
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showUnpermittedFiles: ''
  showUnpermittedVolumes: ''
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
