columnSuffix: null
contentColumnType: text
fieldGroup: 1fbf6371-1871-4eb1-85a2-532ba65a9ece
handle: tizayucaPhone
instructions: ''
name: 'Teléfono Tizayuca'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
