dateModified: 1716498714
email:
  fromEmail: hola@ofeliaexperience.com
  fromName: 'Grupo Ciesc'
  replyToEmail: null
  template: null
  transportSettings:
    apiKey: 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
    categories: ''
  transportType: putyourlightson\sendgrid\mail\SendgridAdapter
fs:
  cdn:
    hasUrls: true
    name: 'Imágenes públicas'
    settings:
      path: '@webroot/assets/images/public_images'
    type: craft\fs\Local
    url: '@web/assets/images/public_images'
meta:
  __names__:
    0c244101-546b-4dfe-8cd5-9f464cf6fe03: 'Meta Description' # Meta Description
    1fbf6371-1871-4eb1-85a2-532ba65a9ece: 'Datos de la empresa' # Datos de la empresa
    2f7a52fb-ecc7-4102-b37f-07c1e3141a2b: 'Fragmento del servicio' # Fragmento del servicio
    3b094a3b-b91d-4668-931f-44fa022c2be6: 'Imagen del artículo' # Imagen del artículo
    3c0e1e4e-7598-4723-9566-831a3692dc3e: 'Dirección Pachuca' # Dirección Pachuca
    4b932bdd-e388-4934-9252-b2bd49692bd2: Logotipo # Logotipo
    006fbfdc-6b86-4dc3-b898-a9b30cd5a062: 'Dirección Querétaro' # Dirección Querétaro
    7d0e2044-bdde-4103-b287-befbcf056b1a: Autor # Autor
    7ea02965-8095-44b1-81ce-0282a9387fe3: 'Grupo Ciesc' # Grupo Ciesc
    8a4111a1-6f82-4333-9d2c-be2325bf6e87: 'Descripción del servicio' # Descripción del servicio
    8afed7eb-1945-4be8-9ca1-0985bbd79418: 'Cuerpo del artículo' # Cuerpo del artículo
    8bb59c3e-d540-4254-8f4a-c4af6c5abdb5: Linkedin # Linkedin
    8c2e8c35-2256-46df-b354-7c44efa39dfa: 'Fragmento del post' # Fragmento del post
    9e660280-513c-453a-838e-ca9453c9a215: 'Link de la empresa' # Link de la empresa
    9f12f92b-d3c9-433e-b204-5ce21c95d573: 'Teléfono Pachuca' # Teléfono Pachuca
    19f32506-7666-4c44-a94d-7b717cb28596: Blog # Blog
    24ad1f78-4194-4ad0-b646-3ea0ea9f4a1d: 'Correo electrónico' # Correo electrónico
    43f226eb-8874-48e8-ac5f-222fbc3ca738: Facebook # Facebook
    50dadc77-662b-4c96-8999-8356ec4d4481: 'Imagen del servicio' # Imagen del servicio
    99d06683-b4dc-4996-af1e-a55db9b88f75: Simple # Simple
    332c3322-a2f6-44b8-a66b-22cadcf0d1c1: 'Public Schema' # Public Schema
    366fe78c-c06c-49b9-b5a6-cb88a0d35c0e: Clientes # Clientes
    964c97bb-a9cc-4e56-9fea-cf94cd23bd3f: 'Imágenes públicas' # Imágenes públicas
    88125bde-16f5-4673-b1a6-d1ba8f34962d: Clientes # Clientes
    867287f4-0358-4ee1-a33d-3c56fb44f327: Clientes # Clientes
    16777690-1a83-4a23-aaf2-5138b7d2617e: Blog # Blog
    ae7929f0-e730-4538-8f63-5a6e530b541e: Servicios # Servicios
    b0568e7a-3e32-4145-82cd-67b09eacf53e: 'Teléfono Tizayuca' # Teléfono Tizayuca
    ba888375-fe91-495d-af9a-291201c2cbd1: 'Global WhatsApp' # Global WhatsApp
    c44e1865-5d0a-429d-be51-84af5e860f1a: Servicios # Servicios
    c6649a02-dc73-41bf-9496-2d6ffb97d502: Blog # Blog
    d62075cc-d1e9-4912-a09e-41e798c6466b: 'Datos de la empresa' # Datos de la empresa
    e0e1d402-f807-4daa-b61d-14470180a90d: Portada # Portada
    e52eea9d-e54c-463e-a654-1fa6e5cf25a5: Common # Common
    e89be7fb-054e-4159-a360-c0c9faa4efbe: 'Grupo Ciesc' # Grupo Ciesc
    f8d4d697-6246-4269-bd95-429ae9eec14f: 'Icono ' # Icono 
    f4832466-aec3-460d-875a-e0295b369b56: Servicios # Servicios
    fe51675c-165a-43b1-a367-0e28d4c642d5: qroPhone # qroPhone
    ff0ed6db-0124-45b3-aa76-69914ea4ee79: 'Categoría del articulo' # Categoría del articulo
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'A nombre de'
      prependSubject: 'New message from Grupo Ciesc'
      successFlashMessage: 'Su mensaje ha sido enviado.'
      toEmail: alfer2506@gmail.com
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.0.0
  sendgrid:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
    settings:
      description: ''
      facebookAppId: ''
      metaTemplate: ''
      removeAlternateUrls: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage: ''
      title:
        -
          __assoc__:
            -
              - key
              - '1'
            -
              - locked
              - '0'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '1'
            -
              - template
              - ' - {{ siteName }}'
      titleSuffix: null
      twitterHandle: ''
  simple-sharing:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Grupo Ciesc'
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: America/Mexico_City
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
